### ISSUE TITLE
Fix static MAC Address

### ISSUE THREAD

**Issue by djvj1** [MiSTer-devel/u-boot_MiSTer#1]
Having multiple Misters on a network will not work (by default) unless mac address is set in the bootloader. Seems the default was set to 02:03:04:05:06:07. If this setting is removed, the physical address will be used instead. Not sure if this was left in accidentally, but it's one thing the user shouldn't have to set.

**Comment by sorgelig** [comment]
There is no physical MAC address in DE10-nano. If fixed MAC address is removed, then random MAC address will be used on every boot, so your MiSTer will get different IP addresses on every boot which is not convenient. If you have several MiSTers and want to use them at the same time, then you need to change default MAC address to other whatever you like.

**Comment by sorgelig** [comment]
Or just use compatible USB WiFi dongle.

**Comment by Lethja** [comment]
If it's any consolation I just ran into this problem myself and wrote a guide on how to manually configure it (https://github.com/MiSTer-devel/MkDocs_MiSTer/pull/76). Ideally someone could write a script to automate these steps later.
